# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: tfsec

on:
  push:
    branches: [ prod, dev, staging ]
  pull_request:
    branches: [ prod ]
  schedule:
    - cron: '16 8 * * 3'

# jobs:
#   tfsec:
#     name: Run tfsec sarif report
#     runs-on: ubuntu-latest
#     permissions:
#       actions: read
#       contents: read
#       security-events: write


jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/create-outputs@v0.0.0-fake
      id: test
    - uses: LouisBrunner/checks-action@v1.6.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Run tfsec
        conclusion: ${{ job.status }}
        output: |
          {"summary":"${{ steps.test.outputs.summary }}"}
          
name: Create Outputs
on:
  push:
    branches:
      - main
jobs:
  create_outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.3"
      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve
      - name: Create Outputs
        run: |
          echo "::set-output name=my_output::$(terraform output my_output)"


#     steps:
#       - name: Clone repo
#         uses: actions/checkout@v3

#       - name: Run tfsec
#         uses: aquasecurity/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
#         with:
#           sarif_file: tfsec.sarif

#       - name: Upload SARIF file
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           # Path to SARIF file relative to the root of the repository
#           sarif_file: tfsec.sarif
